### ISSUE TITLE
I can't run setup.bat on Window

### ISSUE THREAD

**Issue by truongvantoan** [miguelgrinberg/REST-tutorial#13]
Traceback (most recent call last):
  File "virtualenv.py", line 2577, in <module>
    main()
  File "virtualenv.py", line 979, in main
    no_pip=options.no_pip)
  File "virtualenv.py", line 1091, in create_environment
    search_dirs=search_dirs, never_download=never_download)
  File "virtualenv.py", line 611, in install_setuptools
    search_dirs=search_dirs, never_download=never_download)
  File "virtualenv.py", line 583, in _install_req
    cwd=cwd)
  File "virtualenv.py", line 1057, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command E:\Project\MYS\REST-...k\Scripts\python.exe -c "#!python
\"\"\"Bootstra...sys.argv[1:])

" --always-copy -U setuptools failed with error code 1

E:\Project\MYS\REST-tutorial-master>flask\Scripts\pip install -r requirements.txt
'flask\Scripts\pip' is not recognized as an internal or external command,
operable program or batch file

**Comment by miguelgrinberg** [comment]
Not sure if this is related or not, but the `virtualenv.py` script that was included in this repository is old and should not be here anyway. Create your virtual environment according to current instructions and then I think you will be fine.

**Comment by truongvantoan** [comment]
setup.bat has run successfully!
But i get another error:

> E:\Project\MYS\REST-tutorial-master>flask\Scripts\python rest-server.py
> Traceback (most recent call last):
>   File "E:\Project\MYS\REST-tutorial-master\flask\lib\site-packages\werkzeug\serving.py", line 53, in <module>
>     from SocketServer import ThreadingMixIn, ForkingMixIn
> ModuleNotFoundError: No module named 'SocketServer'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "rest-server.py", line 125, in <module>
>     app.run(debug=True)
>   File "E:\Project\MYS\REST-tutorial-master\flask\lib\site-packages\flask\app.py", line 758, in run
>     from werkzeug.serving import run_simple
>   File "E:\Project\MYS\REST-tutorial-master\flask\lib\site-packages\werkzeug\serving.py", line 56, in <module>
>     from socketserver import ThreadingMixIn, ForkingMixIn
> ImportError: cannot import name 'ForkingMixIn'

**Comment by truongvantoan** [comment]
I has comeback commit "Python 2 & 3 compliance - commit 4a4269b87f902adf704eb1ff345e80622d29a293"
And Install again with python 2.7 flow 

> - Install Python 2.7 and git.
> - (Window): python -m pip install -U pip
> - (Window): python get-pip.py "https://pip.pypa.io/en/stable/installing/"
> - (Window): pip install virtualenv
> - Run `setup.sh` (Linux, OS X, Cygwin) or `setup.bat` (Windows)
> - Run `./rest-server.py` to start the server (on Windows use `python rest-server.py` instead)
> - Alternatively, run `./rest-server-v2.py` to start the Flask-RESTful version of the server(on Windows use `python rest-server-v2.py` instead).
> - Open `http://localhost:5000/index.html` on your web browser to run the client
## And installed successfully on window !

**Comment by miguelgrinberg** [comment]
I updated the instructions, at this point in the life of Python 2 it would be a bad idea to focus on that version. I suggest you migrate to Python 3.

**Comment by elsagong** [comment]
Hi Miguel, the tutorial is really awesome, thank you so much, can you help me with this? about rest-server-v2.py, when I type `curl -u miguel:python -i http://localhost:5000/todo/api/v1.o/tasks`, and get the 'uri’ is different from rest-server.py, there is no localhost address and I can't click it, it displayed `"uri": "/todo/api/v1.0/tasks/2"`, I really appreciate it.

Best Regards,
Elsa

**Comment by miguelgrinberg** [comment]
You need to add `absolute=True` to the `Url` field. See the [documentation](https://flask-restful.readthedocs.io/en/latest/api.html#fields.Url).

**Comment by elsagong** [comment]
Incredibly! Thanks so much for your prompt reply!
I am really really appreciate it!
Best wishes to you and your family.

**Comment by elsagong** [comment]
Hi Miguel, Thank you so much for detailed tutorial. If you don't mind, may I know how to design a api of timed tasks in python? 
Thanks in advance.

**Comment by miguelgrinberg** [comment]
This is an old issue that has been addressed in the README file. Closing.
