### ISSUE TITLE
Two minor mistakes from tags v0.1 to v0.7

### ISSUE THREAD

**Issue by jianchao-li** [miguelgrinberg/REST-tutorial#15]
While working through [Writing a Javascript REST Client](https://blog.miguelgrinberg.com/post/writing-a-javascript-rest-client), I noticed two minor mistakes in all tags from `v0.1` to `v0.7`.

The first one is the following `import` statement, which is the old way of importing `Flask-HTTPAuth`.

```python
from flask.ext.httpauth import HTTPBasicAuth
```

For the latest version, it should be

```python
from flask_httpauth import HTTPBasicAuth
```

The second one is that there are two `not_found` functions. Actually the first one should be named `bad_request`.

```python
@app.errorhandler(400)
def bad_request(error):
    return make_response(jsonify( { 'error': 'Bad request' } ), 400)
 
@app.errorhandler(404)
def not_found(error):
    return make_response(jsonify( { 'error': 'Not found' } ), 404)
```

**Comment by miguelgrinberg** [comment]
Yes, I did not intend to retroactively fix the older stages of this tutorial, if you look at the commit history you'll see that I stopped maintaining the tags long ago and have made fixes and improvements as new commits beyond the tags.
