### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by Fragge** [miguelgrinberg/REST-tutorial#23]
Following the installation instructions and installing (using Python 3.9.0) I get the same error as referenced in a previous bug. I saw no response to that comment and open a new issue for this.

I am using Windows PowerShell and Python 3.9.0 (64 bit).
/Fredrik

> E:\Project\MYS\REST-tutorial-master>flask\Scripts\python rest-server.py
> Traceback (most recent call last):
>   File "E:\Project\MYS\REST-tutorial-master\flask\lib\site-packages\werkzeug\serving.py", line 53, in <module>
>     from SocketServer import ThreadingMixIn, ForkingMixIn
> ModuleNotFoundError: No module named 'SocketServer'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "rest-server.py", line 125, in <module>
>     app.run(debug=True)
>   File "E:\Project\MYS\REST-tutorial-master\flask\lib\site-packages\flask\app.py", line 758, in run
>     from werkzeug.serving import run_simple
>   File "E:\Project\MYS\REST-tutorial-master\flask\lib\site-packages\werkzeug\serving.py", line 56, in <module>
>     from socketserver import ThreadingMixIn, ForkingMixIn
> ImportError: cannot import name 'ForkingMixIn'

E:\Project\MYS\REST-tutorial-master>python --version
Python 3.6.4

_Originally posted by @truongvantoan in https://github.com/miguelgrinberg/REST-tutorial/issues/13#issuecomment-356309664_

**Comment by miguelgrinberg** [comment]
Try upgrading flask to latest. The requirements file in this repository is very old, I need to refresh it

**Comment by miguelgrinberg** [comment]
I have updated dependencies to be up to date. Give it a new try.

**Comment by Fragge** [comment]
Pulled the latest from the repo and the app runs. There's seems to be another issue but I'll submit a separate issue for that when I have tested on a couple of more browsers.
Thanks for the quick response!
