### ISSUE TITLE
Cross-Origin Request Blocked

### ISSUE THREAD

**Issue by Fragge** [miguelgrinberg/REST-tutorial#24]
Following the setup steps for Windows I open http://localhost:5000/index.html on my web browser to run the client. The table headings are displayed (Task, Options, etc.) as well as the "Add Task" button. No data is displayed. This is consistent on Firefox, Edge and Internet Explorer.

Using the Firefox browser console I see the following errors:

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:5000/todo/api/v1.0/tasks?_=1641069699513. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 200.

It also says "ajax error 0" which I think is output from the error handler.

This or a similar issue was raised in a [previous issue](https://github.com/miguelgrinberg/REST-tutorial/issues/4#issue-20315777) and attributed to the server and client being run on the same host. I'm new to front end development but after reading about CORS today I think it is rather due to that the endpoints require authentication. As I understand it, "Access-Control-Allow-Origin" needs to be specified on the response (and not as "*") or standard browsers will not accept the response. Non browser clients may not have this issue.

Not sure how to accomplish this in the simplest way though...

**Comment by Fragge** [comment]
I got the data to display without errors by adding Flask-Cors and specifying my current host as the only allowed origin. Top of rest-server.py:

```
#!flask/bin/python
from flask import Flask, jsonify, abort, request, make_response, url_for
from flask_httpauth import HTTPBasicAuth
from flask_cors import CORS                 # Added import of CORS

app = Flask(__name__, static_url_path="")
auth = HTTPBasicAuth()
CORS(app, origins="http://127.0.0.1:5000")  # Set allowed origin for all routes
```

As I see it, it strengthens my theory but is not a solution. Instead I would like to "dynamically" set the allowed origin to the requesting host.

**Comment by miguelgrinberg** [comment]
The `index.html` uses `localhost:5000` to connect to the server. To avoid having a cross-origin situation you have to open the index file as `http://localhost:5000/index.html` and not `http://127.0.0.1/index.html`.

**Comment by Fragge** [comment]
That explains a lot. I thought they were equivalent in all respects. It was wondering why not everyone ran into this issue with the tutorial.

Thanks!
